export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE_CART_DATA = 'REMOVE_CART_DATA';


